# Generated by Django 2.2.10 on 2020-06-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0002_auto_20200621_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
