# Generated by Django 2.2.10 on 2020-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0004_auto_20200622_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash_url',
            field=models.URLField(blank=True),
        ),
    ]
