# Generated by Django 2.2.10 on 2020-06-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0005_auto_20200622_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='hash_id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='hash_url',
        ),
    ]
