# Generated by Django 2.2.10 on 2020-06-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0007_auto_20200622_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='original_url',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='hash_url',
            new_name='shortened_url',
        ),
    ]
