# Generated by Django 2.2.10 on 2020-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0008_auto_20200622_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
