# Generated by Django 2.2.10 on 2020-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortend_url', '0009_auto_20200622_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash_id',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortened_url',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
